[project]
name = "iOSForge Project"
kind = "tweak"
# Hard minimum target: iOS 15.0.
minimum_ios = "15.0"

[theos]
# 上传你自己的 Theos 工程后填写，例如：
# project_dir = "plugin"

# For local builds you can set this path, or simply export THEOS.
# root = "/opt/theos"

[app]
# Fill these in when this repository also contains an Xcode project.
# project = "MyApp.xcodeproj"
# scheme = "MyApp"
configuration = "Release"

