#import <CoreGraphics/CoreGraphics.h>
#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSInteger, ATTouchPhase) {
    ATTouchPhaseDown = 0,
    ATTouchPhaseMove = 1,
    ATTouchPhaseUp = 2,
};

/// The HID monitor also observes frames generated by this process. Recording
/// their exact Mach timestamps lets the floating HUD ignore only those frames
/// without filtering the real touchscreen sender ID (which is device-specific
/// and can be identical to the sender used for accepted synthetic touches).
FOUNDATION_EXPORT void ATTouchDispatcherRegisterSyntheticTimestamp(uint64_t timestamp);
FOUNDATION_EXPORT BOOL ATTouchDispatcherIsSyntheticTimestamp(uint64_t timestamp);
FOUNDATION_EXPORT BOOL ATTouchDispatcherIsSyntheticDispatchInProgress(void);

@interface ATTouchDispatcher : NSObject

+ (instancetype)shared NS_SWIFT_NAME(shared());
+ (instancetype)dispatcherForModule:(NSString *)module NS_SWIFT_NAME(dispatcher(module:));

@property (nonatomic, readonly, getter=isAvailable) BOOL available;
@property (nonatomic, copy, readonly) NSString *diagnosticText;

/// Recreates the event-dispatch client in the process's current foreground or
/// background state and sends one non-touching neutral frame. This avoids the
/// first real touch-down being consumed while the private HID route warms up.
- (BOOL)prepareForDispatch NS_SWIFT_NAME(prepareForDispatch());

/// Holds or releases a power-management assertion that prevents automatic
/// display idle sleep while an automation task is running in the background.
/// Manual power-button locking is not blocked.
- (BOOL)setDisplaySleepPreventionEnabled:(BOOL)enabled NS_SWIFT_NAME(setDisplaySleepPreventionEnabled(_:));

- (BOOL)sendAtX:(CGFloat)x
               y:(CGFloat)y
           phase:(ATTouchPhase)phase NS_SWIFT_NAME(send(x:y:phase:));

/// Releases an in-flight synthetic finger, if any. This prevents a stop or
/// pause transition from leaving the system in a permanent touch-down state.
- (void)cancelActiveTouch NS_SWIFT_NAME(cancelActiveTouch());

/// Releases any in-flight finger with a final UP and tears down the process-wide
/// event-dispatch client. Called immediately after the device-lock gate closes;
/// the client is recreated on the next resume.
- (void)suspendForDeviceLock NS_SWIFT_NAME(suspendForDeviceLock());

- (BOOL)openApplicationWithBundleIdentifier:(NSString *)bundleIdentifier
    NS_SWIFT_NAME(openApplication(bundleIdentifier:));

@end

NS_ASSUME_NONNULL_END
