source 'https://cdn.cocoapods.org/'
platform :ios, '15.0'
project 'Hailuo.xcodeproj'

target 'Hailuo' do
  pod 'AlipaySDK-iOS', '15.8.30'
  pod 'WechatOpenSDK', '2.0.9'
  target 'HailuoTests' do
    inherit! :search_paths
  end
end
