#import <CoreGraphics/CoreGraphics.h>
#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSInteger, ATTouchPhase) {
    ATTouchPhaseDown = 0,
    ATTouchPhaseMove = 1,
    ATTouchPhaseUp = 2,
};

/// The HID monitor also observes frames generated by this process. Recording
/// their exact Mach timestamps lets the floating HUD ignore only those frames
/// without filtering the real touchscreen sender ID (which is device-specific
/// and can be identical to the sender used for accepted synthetic touches).
FOUNDATION_EXPORT void ATTouchDispatcherRegisterSyntheticTimestamp(uint64_t timestamp);
FOUNDATION_EXPORT BOOL ATTouchDispatcherIsSyntheticTimestamp(uint64_t timestamp);

@interface ATTouchDispatcher : NSObject

+ (instancetype)shared NS_SWIFT_NAME(shared());

@property (nonatomic, readonly, getter=isAvailable) BOOL available;
@property (nonatomic, copy, readonly) NSString *diagnosticText;

- (BOOL)sendAtX:(CGFloat)x
               y:(CGFloat)y
           phase:(ATTouchPhase)phase NS_SWIFT_NAME(send(x:y:phase:));

/// Releases an in-flight synthetic finger, if any. This prevents a stop or
/// pause transition from leaving the system in a permanent touch-down state.
- (void)cancelActiveTouch NS_SWIFT_NAME(cancelActiveTouch());

- (BOOL)openApplicationWithBundleIdentifier:(NSString *)bundleIdentifier
    NS_SWIFT_NAME(openApplication(bundleIdentifier:));

@end

NS_ASSUME_NONNULL_END
